[source](https://www.mathworks.com/help/optim/ug/sudoku-puzzles-problem-based.html)

In [ ]:
import numpy as np
import scipy as sp


In [4]:
empty_sudoku = np.array(
   [[0, 0, 1, 0, 0, 0, 0, 0, 2],
    [0, 0, 0, 3, 0, 4, 5, 0, 0],
    [6, 0, 0, 7, 0, 0, 1, 0, 0],
    [0, 4, 0, 5, 0, 0, 0, 0, 0],
    [0, 2, 0, 0, 0, 0, 0, 8, 0],
    [0, 0, 0, 0, 0, 6, 0, 9, 0],
    [0, 0, 5, 0, 0, 9, 0, 0, 4],
    [0, 0, 8, 2, 0, 1, 0, 0, 0],
    [3, 0, 0, 0, 0, 0, 7, 0, 0]]
)

In [9]:
#you can also just turn the matrix into a sparse one in index format, that might be faster
def sudocu_array_to_clues(sudoku_array):
    clues_inds_rows, clues_inds_cols = np.where(sudoku_array>0)
    clues_vals = sudoku_array[clues_inds_rows, clues_inds_cols]
    return clues_inds_rows, clues_inds_cols, clues_vals

sudocu_array_to_clues(empty_sudoku)

(array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8]),
 array([2, 8, 3, 5, 6, 0, 3, 6, 1, 3, 1, 7, 5, 7, 2, 5, 8, 2, 3, 5, 0, 6]),
 array([1, 2, 3, 4, 5, 6, 7, 1, 4, 5, 2, 8, 6, 9, 5, 9, 4, 8, 2, 1, 3, 7]))

In [ ]:
def generate_one_value_constr():
    return

def generate_row_uniq_constr():
    return

def generate_col_uniq_constr():
    return

def generate_block_uniq_constr():
    return

